### PR TITLE
add csv files and work on scraper

### PR DESCRIPTION
**Pull request by moshe742**

### CODE REVIEW

**Comment by gnoam** [comment]
can we merge this?

**Comment by moshe742** [comment]
Not yet, fixed more bugs, and can't push with all data, will remove the data and push tomorrow

**Comment by alonre** [comment]
Hey @moshe742 - any update here?

**Comment by moshe742** [comment]
I didn't upload the last updates yet, and will be able to do this only on the 30th, do you prefer I will close this PR and create a new one or will update this one when I come back?

**Pull request closed without merging**
